### PR TITLE
Update app.js (added input for spotify link)

### PR DESCRIPTION
**Pull request by mohsenemx**
Used `prompt-sync` to get input from user, asking for their spotify link
helps with UX a lot. Also I'll make another pull request for readme updates.

### CODE REVIEW

**Comment by mohsenemx** [comment]
My Readme update Pull Request: [Pull](https://github.com/Shubhamrawat5/spotify-playlist-downloader/pull/6)

**Comment by Shubhamrawat5** [comment]
alright but you've not added "prompt-sync" in dependency. 

Error: Cannot find module 'prompt-sync'

**Comment by Shubhamrawat5** [comment]
Also I think that should be `const prompt = require("prompt-sync")();`

**Comment by mohsenemx** [comment]
Can you fix it yourself? I can't access my PC until end of Feb

**Comment by Shubhamrawat5** [comment]
Okay will check

**Pull request closed without merging**
